## ============================================================
## Dataset documentation
## ============================================================

#' Synthetic Woodcock-Johnson IV look-alike dataset
#'
#' A synthetic dataset generated by \code{\link{simulate_sepa_fake_wj}} that
#' approximates the observed marginal distributions (means, SDs, and ranges)
#' of seven WJ-IV broad ability scores while respecting the qualitative
#' level-elevation / pattern-elevation structure assumed by SEPA.  The original
#' WJ-IV norming data are proprietary; this object provides a fully
#' reproducible, publicly shareable substitute.
#'
#' @format A data frame with 5\,127 rows and 8 columns:
#' \describe{
#'   \item{ID}{Integer person identifier (1--5127).}
#'   \item{LT}{Long-term retrieval broad ability score.}
#'   \item{ST}{Short-term working memory score.}
#'   \item{CP}{Cognitive processing speed score.}
#'   \item{AP}{Auditory processing score.}
#'   \item{VP}{Visual processing score.}
#'   \item{CK}{Comprehension-knowledge score.}
#'   \item{FR}{Fluid reasoning score.}
#' }
#' All domain scores are in a standard score metric (mean \eqn{\approx 100},
#' SD \eqn{\approx 15}) and clipped to the reported empirical range.
#'
#' Three attributes capture the generative parameters:
#' \code{B_loadings} (\eqn{7 \times 4} orthonormal loading matrix),
#' \code{lambda} (PE dimension variances), and \code{sigma_LE} (LE SD).
#'
#' @source Generated by \code{simulate_sepa_fake_wj(n = 5127, seed = 20251127)}.
#'   See \code{data-raw/generate_fake_wj.R} for the exact code.
#'
#' @examples
#' dim(fake_wj)
#' summary(fake_wj[, c("LT","ST","CP","AP","VP","CK","FR")])
"fake_wj"
